# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_article_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
